#base
title: Make the world better!
subtitle: Make lives better!
description: ying-tiger-cai blog

avatarTitle: Tech works!
avatarDesc: ying-tiger-cai

gitment:
    id: b22ce25d5ce7a64c75f8
    secret: b436673061d29934d3182c95da22382154260731

social:
    github: ying-tiger-cai
    twitter: cai_tiger 
    mail: ying123@gmail.com

url: "https://ying-tiger-cai.github.io"

# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#  _post/ 下的文章更换成你自己的文章
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》

permalink: /:year/:month/:title/
# Format
highlighter: rouge

mathjax: true

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: blog homepage

# Navigation buttons in the front page.s
nav:
    - {title: archive, description: archive, url: '/archive'}   
    - {title: tags, description: tags, url: '/tags'}      
    - {title: projects, description: projects, url: '/about'}      
    
# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
